              - name: GitHub Release from Tag
                uses: ghalactic/github-release-from-tag@v5
            

name: Release from tag

on:
  ???

jobs:
  irgendein-name:
    permissions:
      contents: write
